modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/caltinor" #optional
displayURL="https://github.com/caltinor" #optional
logoFile="" #optional
credits="Thanks to the MMD community." #optional
authors="Caltinor" #optional
license="ARR License"

[[mods]] #mandatory
modId="dicemccl" #mandatory
version="1.0" #mandatory
displayName="Corrupted Lands" #mandatory
#updateJSONURL=""
description='''
A SpookyJam Mod.
'''

[[dependencies.enderthing]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.enderthing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"